### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by rebaz36**
## In this Part of the Project, we Implement the following
- Use Gitflow Accordingly
- Set Up Webpack
- Add HTML Content with Minimum Styles ( CSS )
- Add CSS only for Layout

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @rebaz36 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that Doesn't follow the [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) pattern 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rebaz36** [comment]
hey @Davidosky007 thanks for the heads up 
i have updated the branches

**Review by OLIPLICHE — APPROVED** [review]
Hi @rebaz36, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Set up a JavaScript project for the Leaderboard list app👏 👏
- Using Webpack and ES6 feature👏 👏
- Gitflow is correctly used (Pull Request is made from the feature branch into the dev branch) 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebaz36** [comment]
thanks @OLIPLICHE

**Pull request merged**
